######################## default configuration ####################
baseURL = "http://demo.gethugothemes.com/bigspring-light/examplesite/"
title = "Bigspring Light"
theme = "bigspring-light-hugo"
# post pagination
paginate = "3"
# post excerpt
summaryLength = "15"
# unsafe html
[markup.goldmark.renderer]
unsafe = true